### ISSUE TITLE
Appello 16 Giugno

### ISSUE THREAD

**Issue by aisadt** [marilenadaquino/informatica-umanistica#63]
Aisa Di Tullio
Matricola: 0000977299
Sito: PlayMe
Url: https://aisadt.github.io/PlayMe-mymusicwebsite/

**Comment by giulialiberto** [comment]
Jenny Leorato
Matricola: 977882

Giulia Liberto
Matricola: 987030

Sito: byName
https://giulialiberto.github.io/byName/
